#!/usr/bin/perl

use strict;
use warnings;

# extract relationship tables

my %sc=(); # student_course
my %cs=(); # course_student
my %sn=(); # student_name
my %cn=(); # course_name

my $line;
my $url = "http://cgi.cse.unsw.edu.au/~cs2041/13s2/lab/perl/students/enrollments";
open F, "wget -q -O- $url|" or die "failed to fetch enrollment info";
while ($line = <F>) {
    $line =~ s/.{45}$//g;
    $line =~ s/\s{2,}$//g;
    $line =~ /([A-Z]{4}[0-9]{4})\|([0-9]{7})\|(.*)/;
    my ($c_id, $s_id, $s_name) = ($1, $2, $3);
    push @{$sc{$s_id}}, $c_id;
    push @{$cs{$c_id}}, $s_id;
    $sn{$s_id} = $s_name;
}

$url = "http://cgi.cse.unsw.edu.au/~cs2041/13s2/lab/perl/students/course_codes";
open F, "wget -q -O- $url|" or die "failed to fetch course info";
while ($line =<F>) {
    $line =~ /([A-Z]{4}[0-9]{4})\s(.*)$/;
    my ($c_id, $c_name) = ($1, $2);
    $cn{$c_id} = $c_name;
}

# sort tables

my $arrayref;
foreach (keys %sc) {
    $arrayref = $sc{$_};
    @$arrayref = sort { $a cmp $b } @$arrayref;
}
foreach (keys %cs) {
    $arrayref = $cs{$_};
    @$arrayref = sort { $a <=> $b } @$arrayref;
}

# generate html pages with relationship pages

my $OUT;
my $index = "index.html";

if (-f $index) {
    unlink($index);
}
open $OUT, '>>', "index.html" or die "failed to generate index.html";
print { $OUT } "
<!DOCTYPE html>\n<html>\n
  <head><title>Index Page</title></head>
  <body>\n    <h2>All Courses</h2>\n    <ul>\n";
foreach (sort keys %cs) { print { $OUT } "      <li><a href=\"$_.html\">$_ $cn{$_}</a></li>\n" }
print { $OUT } "
    </ul>\n    <h2>All Students</h2>    <ul>\n";
foreach (sort keys %sc) { print { $OUT } "      <li><a href=\"$_.html\">$_ $sn{$_}</a></li>\n" }
print { $OUT } "
    </ul>\n    <hr>\n    <small>generated by chad luo 3423267</small>\n  </body>\n</html>";

foreach (keys %sc) {
    my $file = $_.".html";
    if (-f $file) {
        unlink($file);
    }
    open $OUT, '>>', $file or die "failed to create single student page";
    print { $OUT } "
<!DOCTYPE html>\n<html>\n
  <head><title>Courses taken by $_ $sn{$_}</title></head>\n
  <body>\n    <h2>Courses taken by $_ $sn{$_}</h2>\n    <ul>\n";
    foreach (@{$sc{$_}}) {
        print { $OUT } "      <li><a href=\"$_.html\">$_ $cn{$_}</a></li>\n";
    }
    print { $OUT } "
    </ul>\n    <a href=\"index.html\">Back To Index</a>\n
    <hr>\n    <small>generated by chad luo 3423267</small>\n  </body>\n</html>";
}

foreach (keys %cs) {
    my $file = $_.".html";
    if (-f $file) {
        unlink($file);
    }
    open $OUT, '>>', $file or die "failed to create single course page";
    print { $OUT } "
<!DOCTYPE html>\n<html>\n
  <head><title>Students Enrolled in $_ $cn{$_}</title></head>\n
  <body>\n    <h2>Students Enrolled in $_ $cn{$_}</h2>\n    <ul>\n";
    foreach (@{$cs{$_}}) {
        print { $OUT } "      <li><a href=\"$_.html\">$_ $sn{$_}</a></li>\n";
    }
    print { $OUT } "
    </ul>\n    <a href=\"index.html\">Back To Index</a>\n
    <hr>\n    <small>generated by chad luo 3423267</small>\n  </body>\n</html>";
}
